#!/usr/bin/env bash
# fixing issues arised from using docker
#make the apache server return Hello ALX when quering the root

sudo apt-get update -y
sudo apt-get install -y apache2
sudo /etc/init.d/apache2 start
echo "Hello ALX" | sudo tee -a /var/www/html/index.html
sudo /etc/init.d/apache2 restart
